### ISSUE TITLE
README says this works with ovirt_engine_setup_version set to 4.0 but template file missing for 4.0

### ISSUE THREAD

**Issue by itewk** [oVirt/ovirt-ansible-engine-setup#6]
The README says this works with `ovirt_engine_setup_version: '4.0'` but get the below error when attempting to use.

```
TASK [oVirt.engine-setup : Use the default answerfile] *************************************************************************************
fatal: [rhevm.rhc-lab.iad.redhat.com]: FAILED! => {
    "changed": false,
    "failed": true
}

MSG:

Could not find or access 'answerfile_4.0_basic.txt.j2'
Searched in:
	/root/ansible-rhc_lab/roles/oVirt.engine-setup/templates/answerfile_4.0_basic.txt.j2
	/root/ansible-rhc_lab/roles/oVirt.engine-setup/answerfile_4.0_basic.txt.j2
	/root/ansible-rhc_lab/roles/oVirt.engine-setup/tasks/templates/answerfile_4.0_basic.txt.j2
	/root/ansible-rhc_lab/roles/oVirt.engine-setup/tasks/answerfile_4.0_basic.txt.j2
	/root/ansible-rhc_lab/playbooks/templates/answerfile_4.0_basic.txt.j2
	/root/ansible-rhc_lab/playbooks/answerfile_4.0_basic.txt.j2
```

**Comment by KKoukiou** [comment]
@itewk hi, thanks for reporting this. 
Initially we decided to not support 3.6 and 4.0 with this role, because although the setup was running fine on RHEL I had some problems testing these versions on centos 7.4, because of missing RHV repositories, and I all tests I have for this role are on docker centos 7.4 images.
So, I can either remove, these versions from supported version from the docs, else I can give it a try to use older Centos for the tests for 4.0 and 3.6.
@mwperina @mykaul WDYT? We want to support these versions with this role?

@itewk In any case, until you issue is solved, you can use the custom answerfile option, by including the basic_answerfile.txt.j2. I think it should be work.

**Comment by mwperina** [comment]
Katerina, please remove those versions completely, only 4.1 and 4.2 should be available

@KKoukiou
